apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  namespace: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
        - name: discovery-server
          image: springcommunity/spring-petclinic-discovery-server:latest
          ports:
            - containerPort: 8761
          env:
            - name: CONFIG_SERVER_URL
              value: "http://config-server:8888"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 40
            periodSeconds: 10
          resources:
            requests: { cpu: "150m", memory: "300Mi" }
            limits: { cpu: "300m", memory: "450Mi" }
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  namespace: petclinic
spec:
  selector:
    app: discovery-server
  ports:
    - port: 8761
      targetPort: 8761
