apiVersion: apps/v1
kind: Deployment
metadata:
  name: vets-service
  namespace: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vets-service
  template:
    metadata:
      labels:
        app: vets-service
    spec:
      containers:
        - name: vets-service
          image: springcommunity/spring-petclinic-vets-service:latest
          ports:
            - containerPort: 8083
          env:
            - name: CONFIG_SERVER_URL
              value: "http://config-server:8888"
            - name: EUREKA_SERVER_URL
              value: "http://discovery-server:8761/eureka"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 60
            periodSeconds: 10
          resources:
            requests: { cpu: "150m", memory: "300Mi" }
            limits: { cpu: "300m", memory: "450Mi" }
---
apiVersion: v1
kind: Service
metadata:
  name: vets-service
  namespace: petclinic
spec:
  selector:
    app: vets-service
  ports:
    - port: 8083
      targetPort: 8083
