apiVersion: apps/v1
kind: Deployment
metadata:
  name: visits-service
  namespace: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visits-service
  template:
    metadata:
      labels:
        app: visits-service
    spec:
      containers:
        - name: visits-service
          image: 972379852441.dkr.ecr.us-east-1.amazonaws.com/petclinic/visits-service:latest
          ports:
            - containerPort: 8082
          env:
            - name: CONFIG_SERVER_URL
              value: "http://config-server:8888"
            - name: EUREKA_SERVER_URL
              value: "http://discovery-server:8761/eureka"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 10
          resources:
            requests: { cpu: "150m", memory: "300Mi" }
            limits: { cpu: "300m", memory: "450Mi" }
---
apiVersion: v1
kind: Service
metadata:
  name: visits-service
  namespace: petclinic
spec:
  selector:
    app: visits-service
  ports:
    - port: 8082
      targetPort: 8082
